/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package com.crio.starter;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class App {

  public static void main(String[] args) {
    SpringApplication.run(App.class, args);
    //the main error is that u have chnged the name of the url as memeUrl in MemeEntity change it to just url;
  }
}
/*mongo
  use greetings
  db.memes.drop()
 */
/*
 * curl --location --request POST 'http://localhost:8081/memes/' \--header 'Content-Type: application/json' \--data-raw '{"name": "xyz","url": "https://cwod-assessment-images.s3.ap-south-1.amazonaws.com/images/130.png","caption": "This is a memesss"}'
 */
//curl --location --request POST 'http://localhost:8081/memes/' \--header 'Content-Type: application/json' \--data-raw '{"name": "xyz","url": "https://cwod-assessment-images.s3.ap-south-1.amazonaws.com/images/130.png","caption": "This is a meme"}'
